env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - id: pk
    main: ./cmd/pk
    binary: pk
    goos:
      - linux
    ldflags:
      - -w -s
      - -X prostokat/internal/version.version={{ trimprefix .Version "v" }}
      - -X prostokat/internal/version.gitCommit={{ .Commit }}
    env:
      - GO386=softfloat
      - CGO_ENABLE=0
nfpms:
  - homepage: https://github.com/pedrobarco/prostokat
    description: prostokat is a minimal tilling utility for GNU/Linux
    maintainer: Pedro Barco <pedro.barco@tecnico.ulisboa.pt>
    license: MIT
    formats:
      - apk
      - deb
      - rpm
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
