repos:
- repo: local
  hooks:
  - id: go-build
    name: go-build
    language: system
    entry: make build
  - id: go-test
    name: go-test
    language: system
    entry: make test

- repo: https://github.com/tekwizely/pre-commit-golang
  rev: v1.0.0-beta.1
  hooks:
  - id: golangci-lint-mod
  - id: go-fmt

- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.17.13
  hooks:
  - id: commitizen
    stages: [commit-msg]
